### ISSUE TITLE
运行不成功的几点问题

### ISSUE THREAD

**Issue by MrZhouL** [V-I-C-T-O-R/12306#1]
1. 请问作者运行的python版本；是什么
2.运行fuckeverything.py显示SyntaxError: Non-ASCII character ，加上# -*- coding=utf-8 -*-可以解决但是又报错ImportError: No module named train.login.Login

本人python小白，求解。。谢谢

**Comment by V-I-C-T-O-R** [comment]
请注意:
1.Python的版本为python3，本人系统为ubuntu16.04，python版本是python3.5
2.执行Python项目需到项目根目录下执行(你的importError异常)
3.安装好需要依赖的python库(readme有说明)
祝你运行成功！

**Comment by gitzhou** [comment]
@MrZhouL 
```
pip3 install requests prettytable pillow colorama twilio
```
编辑`configure.py`
```
python3 fuckeverything.py
```

**Comment by V-I-C-T-O-R** [comment]
@MrZhouL 多谢帮忙解答
