### ISSUE TITLE
'IPV' is not in list

### ISSUE THREAD

**Issue by seua** [V-I-C-T-O-R/12306#10]
这是什么信息

**Comment by V-I-C-T-O-R** [comment]
请把具体的异常日志发出来

**Comment by antilosener** [comment]
我也遇到了这个问题

**Comment by antilosener** [comment]
正在为您第1次刷票，当前时间为:2019-01-18 17:07:56

'IPV' is not in list

第50次访问12306网站
----------------------------------------
正在为您第1次刷票，当前时间为:2019-01-18 17:07:56

'IPV' is not in list

第51次访问12306网站
----------------------------------------
正在为您第1次刷票，当前时间为:2019-01-18 17:07:56

'IPV' is not in list

第52次访问12306网站
----------------------------------------
正在为您第1次刷票，当前时间为:2019-01-18 17:07:56

'IPV' is not in list

第53次访问12306网站
----------------------------------------
正在为您第1次刷票，当前时间为:2019-01-18 17:07:56

'IPV' is not in list

第54次访问12306网站
----------------------------------------
正在为您第1次刷票，当前时间为:2019-01-18 17:07:57

'IPV' is not in list

第55次访问12306网站
----------------------------------------
正在为您第1次刷票，当前时间为:2019-01-18 17:07:57

'IPV' is not in list

第56次访问12306网站
----------------------------------------
正在为您第1次刷票，当前时间为:2019-01-18 17:07:57

**Comment by V-I-C-T-O-R** [comment]
把你输入的起始站和终点站说明下，好帮你调试

**Comment by V-I-C-T-O-R** [comment]
@seua @antilosener 原平这个站有点少见，没有收录，更新代码即可解决
