### ISSUE TITLE
第一条request消息就卡住了，无法登陆成功，求助一下

### ISSUE THREAD

**Issue by ahumoon7421** [V-I-C-T-O-R/12306#11]
正在登录...
第1次尝试获取验证图片

Process finished with exit code -1

![image](https://user-images.githubusercontent.com/6998116/51520746-82ff3300-1e5f-11e9-8684-b774ac4e4339.png)

**Comment by V-I-C-T-O-R** [comment]
@ahumoon7421 请贴出具体的异常日志

**Comment by ahumoon7421** [comment]
已经确认环境需要配置proxy。在try前增加proxies的配置并传入request即可。
proxies = {
  "http": "http://10.10.1.10:3128",
  "https": "http://10.10.1.10:1080",
}

r=requests.get("http://icanhazip.com", proxies=proxies)
print r.text

如果需要带密码：
proxies = {
    "http": "http://user:pass@10.10.1.10:3128/",
}

参考解决方案：
http://gohom.win/2016/01/21/proxy-py/

**Comment by V-I-C-T-O-R** [comment]
@ahumoon7421 表示很尴尬-_-
