### ISSUE TITLE
Thread validUsefulProxy 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by yuechenxv** [V-I-C-T-O-R/12306#12]
![image](https://user-images.githubusercontent.com/16622667/51528182-12f9a880-1e71-11e9-8d04-a875b959de6f.png)
![image](https://user-images.githubusercontent.com/16622667/51528205-1f7e0100-1e71-11e9-92a0-bba9d4c5b3ef.png)

**Comment by yuechenxv** [comment]
没有看到错误日志，用list 调用 split 会不会报错

**Comment by V-I-C-T-O-R** [comment]
@yuechenxv 不懂你表达的意思噢，这边运行是没有异常的

**Comment by V-I-C-T-O-R** [comment]
@yuechenxv 多线程传list不会报错，你可以查一下语法。刚改了下多进程的传参
