### ISSUE TITLE
大哥，请问这是什么原因？不明白啊

### ISSUE THREAD

**Issue by herrizd** [V-I-C-T-O-R/12306#14]
[32m正在更新ip池,请稍后...[39m
[33mhttp://www.66ip.cn无效[39m
[33mhttp://www.xicidaili.com无效[39m
[33mhttp://www.goubanjia.com无效[39m
[33mhttp://www.mimiip.com无效[39m
[33mhttp://proxy.coderbusy.com无效[39m
[33mhttp://cn-proxy.com无效[39m
[33mhttp://proxy-list.org/english/index.php无效[39m
[32m正在检查ip可用性...[39m
[32m更新完成[39m
[32m正在登录...[39m
[32m第1次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\lib\arraypad.py)
[39m
[33m验证码识别错误![39m
[32m第2次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\lib\arraypad.py)
[39m
[33m验证码识别错误![39m
[32m第3次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\lib\arraypad.py)
[39m
[33m验证码识别错误![39m
[32m第4次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\lib\arraypad.py)
[39m
[33m验证码识别错误![39m
[32m第5次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\lib\arraypad.py)
[39m
[33m验证码识别错误![39m
[32m第6次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\lib\arraypad.py)
[39m
[33m验证码识别错误![39m
[32m第7次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\lib\arraypad.py)
[39m
[33m验证码识别错误![39m
[32m第8次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\lib\arraypad.py)
[39m
[33m验证码识别错误![39m
[32m第9次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\lib\arraypad.py)
[39m
[33m验证码识别错误![39m
[32m第10次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\lib\arraypad.py)
[39m
[33m验证码识别错误![39m
[31m验证码识别错误![39m
[32m第1次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot identify image file <_io.BytesIO object at 0x06C66BD0>
[39m
[33m验证码识别错误![39m
[32m第2次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot identify image file <_io.BytesIO object at 0x0DB7AA80>
[39m
[33m验证码识别错误![39m
[32m第3次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot identify image file <_io.BytesIO object at 0x0D92A6C0>
[39m
[33m验证码识别错误![39m
[32m第4次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot identify image file <_io.BytesIO object at 0x0DB7AA80>
[39m
[33m验证码识别错误![39m
[32m第5次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot identify image file <_io.BytesIO object at 0x0DB7AA80>
[39m
[33m验证码识别错误![39m
[32m第6次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot identify image file <_io.BytesIO object at 0x0DB7C0C0>
[39m
[33m验证码识别错误![39m
[32m第7次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot identify image file <_io.BytesIO object at 0x0DBF5F00>
[39m
[33m验证码识别错误![39m
[32m第8次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot identify image file <_io.BytesIO object at 0x0D92A6C0>
[39m
[33m验证码识别错误![39m
[32m第9次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot identify image file <_io.BytesIO object at 0x0DB7AA80>
[39m
[33m验证码识别错误![39m
[32m第10次尝试获取验证图片[39m
[32m正在获取验证码..[39m
[33m
cannot identify image file <_io.BytesIO object at 0x06C66BD0>
[39m
[33m验证码识别错误![39m
[31m验证码识别错误![39m
[31m登录失败[39m
[31m登录失败[39m

**Comment by V-I-C-T-O-R** [comment]
@herrizd 可能是由于图片识别失败造成的，你可以选择手动输入识别
