### ISSUE TITLE
12306打码接口

### ISSUE THREAD

**Issue by 12374598858** [V-I-C-T-O-R/12306#16]
https://12306.jiedanba.cn

**Comment by V-I-C-T-O-R** [comment]
@12374598858 你是调用的360接口吧？似乎并不是自身的识别服务

**Comment by 12374598858** [comment]
> @12374598858 你是调用的360接口吧？似乎并不是自身的识别服务

http://12306.jiedanba.cn/12306 建议使用这个地址

**Comment by 12374598858** [comment]
@V-I-C-T-O-R http://12306.jiedanba.cn/12306建议使用这个地址
