### ISSUE TITLE
购票无法提交订单

### ISSUE THREAD

**Issue by zghmvp** [V-I-C-T-O-R/12306#20]
无限循环，这是什么原因呢
----------------------------------------
正在为您第1次刷票，当前时间为:2019-04-17 15:25:55
K512 硬座: 20
已为您查询到可用余票:[车次:K512,出发站:茂名,到达站:广州,出发时间:01:52,到达时间:08:34]
第13次访问12306网站
----------------------------------------
正在为您第1次刷票，当前时间为:2019-04-17 15:25:56
K512 硬座: 20
已为您查询到可用余票:[车次:K512,出发站:茂名,到达站:广州,出发时间:01:52,到达时间:08:34]
第14次访问12306网站
----------------------------------------
正在为您第1次刷票，当前时间为:2019-04-17 15:25:57
K512 硬座: 20
已为您查询到可用余票:[车次:K512,出发站:茂名,到达站:广州,出发时间:01:52,到达时间:08:34]
第15次访问12306网站
----------------------------------------

**Comment by V-I-C-T-O-R** [comment]
@zghmvp 12306最近更新之后很疯狂啊，简直要抓狂。具体得看是不是被一段时间限定了操作。过一段时间就好了，暂时还在试验中
