### ISSUE TITLE
作者，要是让购到票程序自己完成支付，有什么思路吗

### ISSUE THREAD

**Issue by xieende** [V-I-C-T-O-R/12306#23]
作者，要是让购到票程序自己完成支付，有什么思路吗

**Comment by V-I-C-T-O-R** [comment]
@V-I-C-T-O-R 应该是12306登录认证->12306支付接口->12306与第三方授权接口->微信/支付宝/第三方支付/银行认证(银行貌似还得做其它接口提交)授权->支付方接口用户验证->支付方确认支付->方法回调通知支付方->回调通知12306。个人臆测
