### ISSUE TITLE
怎么规避12306 error.html

### ISSUE THREAD

**Issue by ofttryaj** [V-I-C-T-O-R/12306#24]
请求12306的接口地址的时候，莫名其妙返回/mormhweb/logFiles/error.html

**Comment by V-I-C-T-O-R** [comment]
@ofttryaj 访问频次、浏览器在登录之后清除了cookie有时也会出现、同一源ip多cookie等等，只能因地制宜咯，顺着它来

**Comment by ofttryaj** [comment]
谢谢~
