### ISSUE TITLE
儿童票怎么买

### ISSUE THREAD

**Issue by yuze1981** [V-I-C-T-O-R/12306#28]
# 购票人类别（成人票:1,儿童票:2,学生票:3,残军票:4）
PASSENGER_TYPE_CODE = '1'
设置里面只有一个类别，如果要买3个票，两个成人，一个儿童，要怎么设置呢？

**Comment by V-I-C-T-O-R** [comment]
抱歉，暂时没考虑过这种需求，所以没这样设置过。你可以考虑下其他的工具，建议直接12306候补买票

**Comment by yuze1981** [comment]
昨天用的很好，今天就获取不到验证图片了。试了几个小时了，不知道怎么回事，现在还正常吗。

**Comment by V-I-C-T-O-R** [comment]
@yuze1981 更新下代码，希望能抢到漏票
