### ISSUE TITLE
验证码识别错误，最新的代码了

### ISSUE THREAD

**Issue by SamoZ** [V-I-C-T-O-R/12306#29]
![image](https://user-images.githubusercontent.com/25240164/64060071-74011000-cbfa-11e9-99e0-95cc43112e4b.png)

**Comment by yuze1981** [comment]
恩。我的也是，昨天还可以。

**Comment by liangzhdp** [comment]
今天刚安装，第一次运行时可弹出验证码窗口，不过输入正确的代码也通不过。以后再怎么运行就直接报错了。

**Comment by V-I-C-T-O-R** [comment]
@SamoZ @yuze1981 @liangzhdp    更新下代码，希望能抢到漏票

**Comment by liangzhdp** [comment]
谢谢，晚上测试下。

Victor <notifications@github.com> 于 2019年9月3日周二 09:16写道：

**Comment by liangzhdp** [comment]
感谢，好用，好人。

**Comment by SamoZ** [comment]
@V-I-C-T-O-R 我clone了最新的代码，但是还是同样的错误
![image](https://user-images.githubusercontent.com/25240164/64140932-d5aebd80-ce38-11e9-9da1-54e76c7bdd22.png)
这个配置，我尝试了1和3，都报错，是不是我的环境有了问题？

**Comment by V-I-C-T-O-R** [comment]
@SamoZ 你好，这里SELECT_AUTO_CHECK_CAPTHCA = 1本地测试是没有问题的。SELECT_AUTO_CHECK_CAPTHCA = 3这种方式依靠第三方的识别经度，暂时不是很可靠。
建议update下代码再试试，或者给出具体异常
