### ISSUE TITLE
验证码识别是自动识别吗，我这里用windows系统自带的图片阅读器打开了文件。但是点击没效果

### ISSUE THREAD

**Issue by adminSxs** [V-I-C-T-O-R/12306#37]

**Comment by V-I-C-T-O-R** [comment]
@adminSxs 当前支持两种方式:手动输入和第三方AI识别。如果你的系统没有图形组件显示出来的话，可以尝试使用配置为SELECT_AUTO_CHECK_CAPTHCA = 3(前提是你已经注册好了百度AI的账号并创建了应用，个人当前是免费的)。经实践，可以自动登录的概率还是蛮大的，希望对你有用
