### ISSUE TITLE
官方推出候补功能，此工具是否有用。

### ISSUE THREAD

**Issue by cervuswang** [V-I-C-T-O-R/12306#41]
5.22，12306推出候补车票功能，有网友说原理是这样的：
        当12306没票之后，会引导你下候补单，相当于你在12306网站上排了一个队，12306也会告诉你当前排在第几位。一旦12306放票或者有乘客退票了，12306会根据这个线上排队的次序，逐个兑现火车票。而此时在12306查到的结果中余票仍然是0。只有将候补队列全部兑现完成后，还有多余的车票，才会显示在查询的结果中。
      也就是说，在官网满足候选用户后多余的票才会放给第三方抢票软件，所以直接用官方APP候补抢票更快更强。
       如有错误之处，欢迎指正。

**Comment by V-I-C-T-O-R** [comment]
@cervuswang 此项目的定位就是个小工具，暂时对此项功能不可用。至于你说的原理，只能说各有各的说法，具体还得实战中看效果，毕竟没有源码，谁也不知道有没有那么公平。如果错误之处，欢迎交流
