### ISSUE TITLE
我出现这个问题： 获取设备指纹失败,请查询12306设备Id获取url是否需要更新

### ISSUE THREAD

**Issue by adminSxs** [V-I-C-T-O-R/12306#49]
我登录的时候出现这个问题，请问应该怎么修改

**Comment by V-I-C-T-O-R** [comment]
@adminSxs 具体查看readme里的问题描述，浏览器debug模式打开12306后抓取device字符过滤即可找到最新的url，复制该url除去最后一部分时间戳值的区域到本工具对应的文件即可

**Comment by adminSxs** [comment]
> @adminSxs 具体查看readme里的问题描述，浏览器debug模式打开12306后抓取device字符过滤即可找到最新的url，复制该url除去最后一部分时间戳值的区域到本工具对应的文件即可

是用什么浏览器去操作，我在chrome，打开不管在network还是其它的菜单都试过。完全搜不到device相关的东西

**Comment by V-I-C-T-O-R** [comment]
清除cookie和浏览记录后再试
