### ISSUE TITLE
配置邮箱问题

### ISSUE THREAD

**Issue by tzkang** [V-I-C-T-O-R/12306#5]
你好，请问配置邮箱中填写`mail_pass`字段，是单纯的填写账号登陆密码；还是填写第三方授权码？  因为网易还有腾讯邮箱对第三方客户端都是使用授权码登陆，所以想确认一下。

**Comment by V-I-C-T-O-R** [comment]
@tzkang mail_user和mail_pass就是你的邮箱用户名和密码，不过你需要开启比如qq邮箱的smtp服务。目前测试过smtp.qq.com的qq邮箱来发件有效，如程序代码configure.py配置所示

**Comment by tzkang** [comment]
好的，谢谢及时回复。  网易邮箱测试可以吗？  （因为其他邮箱发qq邮箱可以通过微信直接收到消息，而通过qq邮箱发给其他邮箱不太方便接收）

**Comment by V-I-C-T-O-R** [comment]
@tzkang 刚给你测试了一下，163邮箱也可以(登录163邮箱，在安全设置中开启smtp服务).。具体更改如下:
```
mail_host = 'smtp.163.com'
mail_user = '******@163.com'
mail_pass = '******'
mailto_list = ['123456789@qq.com']
```

**Comment by tzkang** [comment]
好的，好的，非常感谢。   就我自己测试的话，如何测试呢？ （以防自己输错了密码之类的）

**Comment by tzkang** [comment]
好的，谢谢。

**Comment by V-I-C-T-O-R** [comment]
@tzkang 一起进步

**Comment by tzkang** [comment]
另外还有一个问题就是，根据配置文件，购票的话，只要填写购票人的身份证号码字段`# 购票人身份证号
PASSENGERS_ID = ['']`，保证这个身份证号码在所使用12306账号的联系人列表中就行，对吧？

**Comment by tzkang** [comment]
哈哈  不不  我向大神学习

**Comment by V-I-C-T-O-R** [comment]
@tzkang 是的，身份证账号得在12306账号中存在

**Comment by tzkang** [comment]
好的。还有一点疑问。（1）如果12306账号中没有改身份证的话是不是在运行程序过程中就会报错？（2）抢票时候的刷新时间一般选择多长好呢（默认是1s，我修改为3s）？（3）近期12306对刷票的IP风景挺厉害的，如果遭遇IP封禁，那是否程序也会运行报错，然后提示呢？ （问题有点多，见谅哈）

**Comment by V-I-C-T-O-R** [comment]
@tzkang 
* ip封了，程序不会抛异常(至少我暂时没见到)
* 抢票的话，2秒，3秒都可以，看你喜欢哈
* 如果12306账号中的身份证和你配置的身份证对不上，那是没法提交的

**Comment by gitzhou** [comment]
@V-I-C-T-O-R   一个简单的问题… 如果IP被封了 程序会有什么反应么。。是会有提示、报错？还是什么都不显示 依旧一条一条的刷 “正在为您第XXX次刷票…”

**Comment by tzkang** [comment]
对的 是@gitzhou 表述的意思。  （如果没有异常抛出，或者错误提示，然后前端显示又还是在刷票，那就有点误导了）

**Comment by V-I-C-T-O-R** [comment]
@tzkang @gitzhou 目前看来，是正常运行状态，也就是你说的依旧一条一条的刷 “正在为您第XXX次刷票…”（分流抢票cdn封了也是在正常刷票-_-）。现在只能弄到免费的代理ip，建议还是频率不要太高，免费的东西还是得爱护

**Comment by tzkang** [comment]
哦哦 好的，谢谢。

**Comment by gitzhou** [comment]
@V-I-C-T-O-R  明白了 多谢 😄
