### ISSUE TITLE
试过高铁票抢到了，K开头的火车无座票试了好像抢不了

### ISSUE THREAD

**Issue by 695290484** [V-I-C-T-O-R/12306#54]
在官网上能看到无座还有票，但是一直在刷抢不到。

**Comment by V-I-C-T-O-R** [comment]
@695290484 无座也得抢了么Q_Q。按照设定是硬座没有了就是无座，有座就能刷。实在是没有，那就是缓存

**Comment by 695290484** [comment]
@V-I-C-T-O-R 还没到实战的时候，到时候能抢到无座的都开心哦- -谢谢大佬的工作！

**Comment by V-I-C-T-O-R** [comment]
@695290484 都是在前人之上做的优化改进，共同进步，一起回家。能用则最好，不能用也不要灰心
