### ISSUE TITLE
No matching distribution found for matplotlib==3.0.2 (from -r requirements.txt (line 14))

### ISSUE THREAD

**Issue by DolphinQuan** [V-I-C-T-O-R/12306#57]
运行pip install -r requirements.txt，报的错误，本地有python2.7,3.7.3,还需要配置什么么

**Comment by Slience-eye** [comment]
我也遇到了，找不到对应版本，您怎么解决的

**Comment by Slience-eye** [comment]
你绝对是用的Python2版本的,你试试用pip3 install -r requirements.txt，就不会报错了，原因在于你的机子里有Python2和Python3两个版本，而直接用pip install -r requirements.txt调用的是python2的，所以没这个版本。

**Comment by DolphinQuan** [comment]
@Slience-eye 使用这个pip3 install -r requirements.txt 也还是不行啊，求救啊

**Comment by V-I-C-T-O-R** [comment]
@DolphinQuan 检查python对应的版本和指令，google或百度都可以找到对应的解决方案。如果pip3也不对，检查pip3是否指向的是python2版本，如果是，找到对应的python3的绝对路径下的pip去执行install指令，希望对你有用。

**Comment by Slience-eye** [comment]
安装Pythonpip3依赖等等的方法https://blog.csdn.net/dengpeiyi2012/article/details/91993990安装完以后再试试pip3 install -rrequirements.txt发自我的华为手机-------- 原始邮件 --------主题：Re: [V-I-C-T-O-R/12306] No matching distribution found for matplotlib==3.0.2 (from -r requirements.txt (line 14)) (#57)发件人：Dahui Quan 收件人：V-I-C-T-O-R/12306 <12306@noreply.github.com>抄送：Slience-eye ,Mention @Slience-eye 使用这个pip3 install -r requirements.txt 也还是不行啊，求救啊
