### ISSUE TITLE
刷一会儿票就会获取乘客信息失败

### ISSUE THREAD

**Issue by ybyangjian** [V-I-C-T-O-R/12306#59]
正在为您第1次刷票，当前时间为:2019-12-19 14:04:13
2020-01-17 D3072 二等座: *
已为您查询到可用余票:[日期:2020-01-17,车次:D3072,出发站:上海南,到达站:重庆北,出发时间:06:29,到达时间:19:15]
提交订单请求成功!
failed to visit https://kyfw.12306.cn/otn/confirmPassenger/initDc
getPassengerDTOs: 获取乘客信息失败
第30次访问12306网站

**Comment by V-I-C-T-O-R** [comment]
@ybyangjian 12306限制了频率
