### ISSUE TITLE
配置好之后一直重复第一次刷票是为什么？

### ISSUE THREAD

**Issue by morning71** [V-I-C-T-O-R/12306#62]
第7次访问12306网站
----------------------------------------
正在为您第1次刷票，当前时间为:2019-12-23 15:50:31

'MXA' is not in list

多次访问一直显示第一次刷票，并且报错MXA is not in list

**Comment by morning71** [comment]
看了下源码，似乎是城市编码里面找不到MXA这个城市，但是问题是我订的车票为厦门-抚州，这两个城市均不是MXA这个code的啊

**Comment by V-I-C-T-O-R** [comment]
@morning71 更新代码或者自行添加到列表里面，梅州西-_-

**Comment by morning71** [comment]
好的，我看看，多谢=v=
