### ISSUE TITLE
更新IP池问题

### ISSUE THREAD

**Issue by tzkang** [V-I-C-T-O-R/12306#7]
作者大大你好，又来打扰了。  还有一个疑问就是在程序启动时候，就开始验证IP池中的IP是否有效，但是测试结果都是：
正在更新ip池,请稍后...
http://www.66ip.cn无效
http://www.xicidaili.com无效
http://www.goubanjia.com无效
http://www.kuaidaili.com无效
http://www.mimiip.com无效

请问这有什么影响吗？

**Comment by gitzhou** [comment]
从README里贴的log看。。貌似是没有影响的  我这也是一样的

**Comment by tzkang** [comment]
嗯嗯，好的，谢谢@gitzhou啦。  你抢到票了不？

**Comment by gitzhou** [comment]
@tzkang  没… 我总是感觉我被Ban IP了… 😭

**Comment by V-I-C-T-O-R** [comment]
是这样的，这些IP池地址是readme中说明的开源代理池源码中的url。我download了它的代码，然后剥离出了它里面寻找可用IP池的过程和验证地址可用性的过程，直接嵌入到本项目中了。你们看到的url失效确实是其中的免费代理不响应了，但是对我们没有影响，可用的代理IP被保存到了sqlite里面，所以不用担心。另外你要是想检测本工具有没有被Ban掉，直接找哪天哪趟车有票的来刷，看看能不能刷到。就能知道有没有被Ban了（不好意思，手机客户端，没法@人，见谅）

**Comment by gitzhou** [comment]
@V-I-C-T-O-R   十分感谢 明白了  😄

**Comment by tzkang** [comment]
@V-I-C-T-O-R 非常感谢耐心的作者
