### ISSUE TITLE
'NoneType' object is not subscriptable 怎么解决呢？

### ISSUE THREAD

**Issue by liangyongrui** [V-I-C-T-O-R/12306#8]
正在为您第1次刷票，当前时间为:2019-01-17 17:02:40
K589 硬卧: 1
已为您查询到可用余票:[车次:K589,出发站:北京西,到达站:华蓥,出发时间:10:30,到达时间:13:36]

'NoneType' object is not subscriptable

第312次访问12306网站

![Uploading image.png…]()

**Comment by V-I-C-T-O-R** [comment]
@liangyongrui 这个估计是长时间刷票之后，偶然12306出现的bad response问题。你可以调试一下在对应的代码出多加几个捕获或判断，借以避免出现这种提示
