### ISSUE TITLE
座位选择问题

### ISSUE THREAD

**Issue by route-nice** [V-I-C-T-O-R/12306#9]
座位选择的时候选1A，如果1A已经卖了，是不是就抢不到了

**Comment by V-I-C-T-O-R** [comment]
限定好D,C,G车次，A代表的只是个代号，代表你想定的是A位置的位置，并不是具体哪一排的A。如果A类位置没有了，那就会订单座位无法提交，继续再刷票或者你不选座位，12306帮你随机弄一个，看它的策略。
